output_path: "."
llp_mH: 0.0
llp_mS: 0.0
min_jet_pt: 40
max_jet_pt: 500
rename_branches:
  nn_jet_index: jet_jetIndex
  jet_pT: jet_pt
  llp_pT: llp_pt
  track_pT: track_pt
  cluster_jetIndex: clus_jetIndex
  HLT_jet_pT: HLT_jet_pt
signal_branches:
  - llp_pT
  - llp_eta
  - llp_phi
  - llp_Lxy
  - llp_Lz
  - jet_pT
  - jet_eta
  - jet_phi
  - jet_isClean_LooseBadLLP
  - cluster_jetIndex
  - clus_pt
  - clus_eta
  - clus_phi
  - clus_time
  - clus_l1ecal
  - clus_l1hcal
  - clus_l2ecal
  - clus_l2hcal
  - clus_l3ecal
  - clus_l3hcal
  - clus_l4ecal
  - clus_l4hcal
  - track_jetIndex
  - track_pT
  - track_eta
  - track_phi
  - track_chiSquared
  - track_d0
  - track_PixelShared
  - track_PixelHoles
  - track_PixelHits
  - track_SCTHits
  - track_SCTHoles
  - track_SCTShared
  - track_vertex_nParticles
  - track_z0
  - MSeg_etaPos
  - MSeg_phiPos
  - MSeg_etaDir
  - MSeg_phiDir
  - MSeg_t0
  - MSeg_jetIndex
  - MSeg_chiSquared
  - mcEventWeight
  - runNumber
  - eventNumber
bib_branches:
  - jet_pT
  - jet_eta
  - jet_phi
  - jet_isClean_LooseBadLLP
  - cluster_jetIndex
  - clus_pt
  - clus_eta
  - clus_phi
  - clus_time
  - clus_l1ecal
  - clus_l1hcal
  - clus_l2ecal
  - clus_l2hcal
  - clus_l3ecal
  - clus_l3hcal
  - clus_l4ecal
  - clus_l4hcal
  - track_jetIndex
  - track_pT
  - track_eta
  - track_phi
  - track_chiSquared
  - track_d0
  - track_PixelShared
  - track_PixelHoles
  - track_PixelHits
  - track_SCTHits
  - track_SCTHoles
  - track_SCTShared
  - track_vertex_nParticles
  - track_z0
  - MSeg_etaPos
  - MSeg_phiPos
  - MSeg_etaDir
  - MSeg_phiDir
  - MSeg_t0
  - MSeg_jetIndex
  - MSeg_chiSquared
  - runNumber
  - eventNumber
  - HLT_jet_pT
  - HLT_jet_eta
  - HLT_jet_phi
  - HLT_jet_isBIB
qcd_branches:
  - jet_pT
  - jet_eta
  - jet_phi
  - jet_isClean_LooseBadLLP
  - cluster_jetIndex
  - clus_pt
  - clus_eta
  - clus_phi
  - clus_time
  - clus_l1ecal
  - clus_l1hcal
  - clus_l2ecal
  - clus_l2hcal
  - clus_l3ecal
  - clus_l3hcal
  - clus_l4ecal
  - clus_l4hcal
  - track_jetIndex
  - track_pT
  - track_eta
  - track_phi
  - track_chiSquared
  - track_d0
  - track_PixelShared
  - track_PixelHoles
  - track_PixelHits
  - track_SCTHits
  - track_SCTHoles
  - track_SCTShared
  - track_vertex_nParticles
  - track_z0
  - MSeg_etaPos
  - MSeg_phiPos
  - MSeg_etaDir
  - MSeg_phiDir
  - MSeg_t0
  - MSeg_jetIndex
  - MSeg_chiSquared
  - mcEventWeight
  - runNumber
  - eventNumber
