output_path: "."
llp_mH: 0.0
llp_mS: 0.0
signal_branches:
  - llp_pT
  - llp_eta
  - llp_phi
  - llp_Lxy
  - llp_Lz
  - jet_pT
  - jet_eta
  - jet_phi
  - jet_isClean_LooseBadLLP
  - jet_nn_calRatio_main_sig_highMass_v3Adv
  - jet_nn_calRatio_main_sig_lowMass_v3Adv
  - jet_nn_calRatio_main_bib_highMass_v3Adv
  - jet_nn_calRatio_main_bib_lowMass_v3Adv
  - jet_nn_calRatio_main_qcd_highMass_v3Adv
  - jet_nn_calRatio_main_qcd_lowMass_v3Adv
  - cluster_jetIndex
  - clus_pt
  - clus_eta
  - clus_phi
  - clus_time
  - clus_l1ecal
  - clus_l1hcal
  - clus_l2ecal
  - clus_l2hcal
  - clus_l3ecal
  - clus_l3hcal
  - clus_l4ecal
  - clus_l4hcal
  - track_jetIndex
  - track_pT
  - track_eta
  - track_phi
  - track_chiSquared
  - track_d0
  - track_PixelHits
  - track_SCTHits
  - track_SCTHoles
  - track_SCTShared
  - track_vertex_nParticles
  - track_z0
  - MSeg_etaPos
  - MSeg_phiPos
  - MSeg_etaDir
  - MSeg_phiDir
  - MSeg_t0
  - MSeg_jetIndex
  - MSeg_chiSquared
  - mcEventWeight
  - runNumber
  - eventNumber
bib_branches:
  - jet_pT
  - jet_eta
  - jet_phi
  - jet_isClean_LooseBadLLP
  - jet_nn_calRatio_main_sig_highMass_v3Adv
  - jet_nn_calRatio_main_sig_lowMass_v3Adv
  - jet_nn_calRatio_main_bib_highMass_v3Adv
  - jet_nn_calRatio_main_bib_lowMass_v3Adv
  - jet_nn_calRatio_main_qcd_highMass_v3Adv
  - jet_nn_calRatio_main_qcd_lowMass_v3Adv
  - cluster_jetIndex
  - clus_pt
  - clus_eta
  - clus_phi
  - clus_time
  - clus_l1ecal
  - clus_l1hcal
  - clus_l2ecal
  - clus_l2hcal
  - clus_l3ecal
  - clus_l3hcal
  - clus_l4ecal
  - clus_l4hcal
  - track_jetIndex
  - track_pT
  - track_eta
  - track_phi
  - track_chiSquared
  - track_d0
  - track_PixelHits
  - track_SCTHits
  - track_SCTHoles
  - track_SCTShared
  - track_vertex_nParticles
  - track_z0
  - MSeg_etaPos
  - MSeg_phiPos
  - MSeg_etaDir
  - MSeg_phiDir
  - MSeg_t0
  - MSeg_jetIndex
  - MSeg_chiSquared
  - runNumber
  - eventNumber
qcd_branches:
  - jet_pT
  - jet_eta
  - jet_phi
  - jet_isClean_LooseBadLLP
  - jet_nn_calRatio_main_sig_highMass_v3Adv
  - jet_nn_calRatio_main_sig_lowMass_v3Adv
  - jet_nn_calRatio_main_bib_highMass_v3Adv
  - jet_nn_calRatio_main_bib_lowMass_v3Adv
  - jet_nn_calRatio_main_qcd_highMass_v3Adv
  - jet_nn_calRatio_main_qcd_lowMass_v3Adv
  - cluster_jetIndex
  - clus_pt
  - clus_eta
  - clus_phi
  - clus_time
  - clus_l1ecal
  - clus_l1hcal
  - clus_l2ecal
  - clus_l2hcal
  - clus_l3ecal
  - clus_l3hcal
  - clus_l4ecal
  - clus_l4hcal
  - track_jetIndex
  - track_pT
  - track_eta
  - track_phi
  - track_chiSquared
  - track_d0
  - track_PixelHits
  - track_SCTHits
  - track_SCTHoles
  - track_SCTShared
  - track_vertex_nParticles
  - track_z0
  - MSeg_etaPos
  - MSeg_phiPos
  - MSeg_etaDir
  - MSeg_phiDir
  - MSeg_t0
  - MSeg_jetIndex
  - MSeg_chiSquared
  - mcEventWeight
  - runNumber
  - eventNumber
