name: ci

on: [workflow_dispatch, push, pull_request_target]

jobs:
    flake8:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Setup python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install flake8
        - name: Lint with flake8
          run: |
            flake8 --ignore=E501,W503            

    test:
        runs-on: ubuntu-latest
        needs: flake8
        steps:
        - uses: actions/checkout@v3
        - name: Setup python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: Cache pip packages
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install .[wsl2,test]
              pip list
        - name: Test with pytest
          run: |
            pytest